---
commitizen:
  breaking_change_exclamation_in_title: true
  gpg_sign: true
  major_version_zero: true
  name: cz_conventional_commits
  tag_format: $version
  update_changelog_on_bump: true
  version: 0.2.0
  version_scheme: semver
